const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

function generatePayslip(payroll, outputPath) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    // Header
    doc.fontSize(20).text("Payslip", { align: "center", underline: true });
    doc.moveDown();

    // Employee info
    doc.fontSize(12).text(`Employee ID: ${payroll.employee}`);
    doc.text(
      `Period: ${new Date(payroll.periodStart).toDateString()} - ${new Date(
        payroll.periodEnd
      ).toDateString()}`
    );
    doc.text(
      `Generated At: ${new Date(
        payroll.generatedAt || Date.now()
      ).toDateString()}`
    );
    doc.moveDown();

    // Salary summary
    doc.fontSize(14).text("Salary Summary", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).text(`Basic Salary: ${payroll.basicSalary.toFixed(2)}`);
    doc.text(`Allowances: ${payroll.allowances.toFixed(2)}`);
    doc.text(`Overtime: ${payroll.overtime.toFixed(2)}`);
    doc.text(`Gross Salary: ${payroll.grossSalary.toFixed(2)}`);
    doc.moveDown();

    // Deductions
    doc.fontSize(14).text("Deductions", { underline: true });
    doc.moveDown(0.5);
    if (payroll.deductions && payroll.deductions.length > 0) {
      payroll.deductions.forEach((d) => {
        doc.fontSize(12).text(`${d.name}: ${d.amount.toFixed(2)}`);
      });
    } else {
      doc.fontSize(12).text("No deductions");
    }
    doc.moveDown();
    doc.text(`Total Deductions: ${payroll.totalDeductions.toFixed(2)}`);
    doc.moveDown();

    // Net Pay
    doc.fontSize(14).text(`NET PAY: ${payroll.netSalary.toFixed(2)}`, {
      underline: true,
      align: "right",
    });
    doc.moveDown(2);

    // Footer
    doc
      .fontSize(10)
      .fillColor("gray")
      .text("Generated by Marline's system", { align: "center" });

    doc.end();

    stream.on("finish", () => resolve(outputPath));
    stream.on("error", reject);
  });
}

module.exports = { generatePayslip };
